/**:
  ros__parameters:
    topic_imu: /boxi/livox/imu
    acc_ratio: false 
    lidars: ["hesai"]
    hesai:
      topic_lidar: /boxi/hesai/points
      lidar_type: Hesai
      scan_line: 32
      blind: 0.5
      q_lb: [0.00122352, -0.70514220, 0.70906315, -0.00155726]
      t_lb: [-0.01919177, -0.00717359, 0.13830923]
      w_pt: 0.01
    livox:
      topic_lidar: /boxi/livox/points
      lidar_type: Mid360Boxi
      scan_line: 4
      blind: 0.5
      q_lb: [0.9999859462903373, 0.0009368971075961205, 0.0014695456614890199, 0.005006983241176387]
      t_lb:  [0.006519576780980849, 0.02440717559132296, -0.041714503937502645]
      w_pt: 0.01      
    lidar_time_offset: 0.0

    knot_hz: 100
    if_lidar_only: false
    
    ds_scan_voxel: 0.5
    point_filter_num: 1
    nn_thresh: 0.5
    coeff_cov: 3.0
    num_nn: 5

    ds_lm_voxel: 0.5
    cube_len: 1000.0

    cov_P0: 0.02
    cov_RCP_pos_old: 0.5
    cov_RCP_ort_old: 0.5
    cov_RCP_pos_new: 1.0
    cov_RCP_ort_new: 1.0
    std_sys_pos: 0.1
    std_sys_ort: 0.1
    cov_acc: [1.0,1.0,1.0]
    cov_gyro: [0.1,0.1,0.1]      
    cov_ba: [0.2, 0.2, 0.2]
    cov_bg: [0.2, 0.2, 0.2]      
    n_iter: 1   
    num_points_upd: 300

    if_save_results: true
    res_file_path: /home/yeah2/Documents/eval_benchmark/bm_gt_test/PIL1_est.txt
