/**:
  ros__parameters:
    topic_imu: /os_cloud_node/imu
    acc_ratio: false  
    lidars: ["Ouster"]
    Ouster:
      topic_lidar: /os_cloud_node/points
      lidar_type: Ouster
      scan_line: 128
      blind: 0.5
      q_lb: [1.0, 0.0, 0.0, 0.0]      
      t_lb: [-0.014, 0.012, 0.015]    
      w_pt: 0.05 
    lidar_time_offset: 0.0

    knot_hz: 100
    if_lidar_only: false  
    
    ds_scan_voxel: 0.1
    point_filter_num: 1
    nn_thresh: 0.5
    coeff_cov: 10.0
    num_nn: 8

    ds_lm_voxel: 0.5
    cube_len: 1000.0

    cov_P0: 0.02
    cov_RCP_pos_old: 0.1
    cov_RCP_ort_old: 0.1
    cov_RCP_pos_new: 1.0
    cov_RCP_ort_new: 1.0
    std_sys_pos: 0.2
    std_sys_ort: 0.1
    cov_acc: [1.0,1.0,1.0]
    cov_gyro: [0.1,0.1,0.1]     
    cov_ba: [0.2, 0.2, 0.2]
    cov_bg: [0.2, 0.2, 0.2]      
    n_iter: 1
    num_points_upd: 300

    if_save_results: false
    topic_gt: /topic_name
    res_file_path: /path/to/results.txt
    q_l_gt: [1.0, 0.0, 0.0, 0.0]        
    t_l_gt: [0.0, 0.0, 0.0]        