/**:
  ros__parameters:
    topic_imu: /vn200/imu
    acc_ratio: false  
    lidars: ["Ouster"]
    Ouster:
      topic_lidar: /os_cloud_node/points
      lidar_type: Ouster
      scan_line: 64
      blind: 0.5
      q_lb: [0.0139870449048335, -0.999880550171830, 0.00563136142854900, 0.00339642920862035]
      t_lb: [0.0484694014435750, -0.0313099101543345, -0.0187614619618876]
      w_pt: 0.5
    lidar_time_offset: 0.1

    knot_hz: 100
    if_lidar_only: false
    
    ds_scan_voxel: 0.5
    point_filter_num: 2
    nn_thresh: 0.5
    coeff_cov: 2.0
    num_nn: 5

    ds_lm_voxel: 0.5
    cube_len: 2000.0

    cov_P0: 0.02
    cov_RCP_pos_old: 0.1
    cov_RCP_ort_old: 0.1
    cov_RCP_pos_new: 1.0
    cov_RCP_ort_new: 1.0
    std_sys_pos: 0.2
    std_sys_ort: 0.1
    cov_acc: [1.0,1.0,1.0]
    cov_gyro: [0.1,0.1,0.1]     
    cov_ba: [0.2, 0.2, 0.2]
    cov_bg: [0.2, 0.2, 0.2]      
    n_iter: 1
    num_points_upd: 500